trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: Docker@2
  inputs:
    containerRegistry: 'Github Container Registry'
    repository: 'moutansos/twitchstatusapi'
    command: 'buildAndPush'
    Dockerfile: './Dockerfile'
    buildContext: '.'
    tags: |
      latest
      $(Build.BuildId)

- script: |
    sed -i.bak "s/\${buildid}/$(Build.BuildId)/" ./kube.yml
    mkdir ./dist
  displayName: 'Kubernetes Config File Container Tag Specification'

- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact publish kubernetes config'
  inputs:
    PathtoPublish: ./kube.yml
    ArtifactName: kube 
